# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4ae230378eeb5eca4dbb6ce5d69084f2c7414465554c9191b63e8e9e0e35c78fb38d00df3ef2ff1f9fb680296500d1375b5bc6c387654610e149d3e85aa00c4

test:
  secret_key_base: 5558aaf3bb032773cf3a9af92b225deb7682fb0342b5320ed2ce477701242517bacdd2f57c33ec120651a3cfa4c455992c185fc80535b5dae1b35f44f9553d22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
